name: CI

on:
  push:
    paths-ignore:
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'LICENSE*'
      - '.idea/**'
      - '.vscode/**'
      - '.npmignore'
      - 'action.yml'
      - 'README.md'

jobs:
  test_and_update_dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm test
      # if all above passes then create the dist and push it to ensure that
      # the latest dist code is available
      - run: npm run ncc
      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Updated distrubition.