name: Release

on:
  workflow_dispatch:

jobs:

  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          publish_latest_tag: true